###############################################################################
# Created by write_sdc
# Tue Jul 28 18:51:47 2026
###############################################################################
current_design water_chip_ai
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 10.0000 [get_ports {clk}]
set_clock_transition 0.1500 [get_clocks {clk}]
set_clock_uncertainty 0.2500 clk
set_propagated_clock [get_clocks {clk}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {arsenic_sensor[0]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {arsenic_sensor[1]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {arsenic_sensor[2]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {arsenic_sensor[3]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {arsenic_sensor[4]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {arsenic_sensor[5]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {arsenic_sensor[6]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {arsenic_sensor[7]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {cadmium_sensor[0]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {cadmium_sensor[1]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {cadmium_sensor[2]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {cadmium_sensor[3]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {cadmium_sensor[4]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {cadmium_sensor[5]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {cadmium_sensor[6]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {cadmium_sensor[7]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {chromium_sensor[0]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {chromium_sensor[1]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {chromium_sensor[2]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {chromium_sensor[3]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {chromium_sensor[4]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {chromium_sensor[5]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {chromium_sensor[6]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {chromium_sensor[7]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {lead_sensor[0]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {lead_sensor[1]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {lead_sensor[2]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {lead_sensor[3]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {lead_sensor[4]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {lead_sensor[5]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {lead_sensor[6]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {lead_sensor[7]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mercury_sensor[0]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mercury_sensor[1]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mercury_sensor[2]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mercury_sensor[3]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mercury_sensor[4]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mercury_sensor[5]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mercury_sensor[6]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mercury_sensor[7]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rst}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {contamination_alarm}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {contamination_alarm}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {clk}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {rst}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {arsenic_sensor[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {arsenic_sensor[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {arsenic_sensor[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {arsenic_sensor[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {arsenic_sensor[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {arsenic_sensor[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {arsenic_sensor[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {arsenic_sensor[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {cadmium_sensor[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {cadmium_sensor[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {cadmium_sensor[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {cadmium_sensor[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {cadmium_sensor[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {cadmium_sensor[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {cadmium_sensor[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {cadmium_sensor[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chromium_sensor[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chromium_sensor[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chromium_sensor[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chromium_sensor[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chromium_sensor[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chromium_sensor[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chromium_sensor[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chromium_sensor[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {lead_sensor[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {lead_sensor[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {lead_sensor[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {lead_sensor[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {lead_sensor[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {lead_sensor[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {lead_sensor[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {lead_sensor[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mercury_sensor[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mercury_sensor[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mercury_sensor[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mercury_sensor[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mercury_sensor[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mercury_sensor[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mercury_sensor[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mercury_sensor[0]}]
set_timing_derate -early 0.9500
set_timing_derate -late 1.0500
###############################################################################
# Design Rules
###############################################################################
set_max_transition 0.7500 [current_design]
set_max_fanout 10.0000 [current_design]
